version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:xnjtUpdrC2V8q4URN2MbzNlEMHr9CBZnB2WwwzoNMko=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=search_ncgws
      - DB_USERNAME=root
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: search_ncgws
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
